# Generated by Django 4.2.8 on 2023-12-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Following_User_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=256, unique=True, verbose_name="用户名"),
                ),
                ("bio", models.CharField(max_length=256, null=True, verbose_name="爱好")),
                (
                    "image",
                    models.ImageField(null=True, upload_to="users", verbose_name="头像"),
                ),
                ("follow", models.BooleanField(default=False, verbose_name="关注")),
                (
                    "huser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="原用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "关注的人",
                "verbose_name_plural": "关注的人",
                "db_table": "following_users",
            },
        ),
    ]
