# Generated by Django 4.2.8 on 2023-12-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="following_user_info",
            name="username",
            field=models.CharField(max_length=256, verbose_name="用户名"),
        ),
    ]
