# Generated by Django 4.2.8 on 2023-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=256, verbose_name="用户名"),
        ),
    ]
