# Generated by Django 4.2.8 on 2023-12-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userinfo_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=256, unique=True, verbose_name="用户名"),
        ),
    ]
