# Generated by Django 4.2.8 on 2023-12-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userinfo_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="token",
            field=models.CharField(default="", max_length=256, verbose_name="token"),
        ),
    ]
