# Generated by Django 4.2.8 on 2023-12-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userinfo_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="token",
            field=models.TextField(default="", verbose_name="token"),
        ),
    ]
