# Generated by Django 4.2.8 on 2023-12-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_userinfo_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="following",
            field=models.JSONField(default=list, verbose_name="关注的人"),
        ),
    ]
