# Generated by Django 4.2.8 on 2023-12-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userinfo_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="following",
        ),
    ]
