# Generated by Django 4.2.8 on 2023-12-08 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlesInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=256, unique=True, verbose_name="标称"),
                ),
                ("title", models.CharField(max_length=256, verbose_name="标题")),
                ("description", models.CharField(max_length=256, verbose_name="描述")),
                ("body", models.TextField(verbose_name="主体内容")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("favorited", models.BooleanField(default=False, verbose_name="喜欢")),
                (
                    "favoritesCount",
                    models.IntegerField(default=0, verbose_name="被喜欢次数"),
                ),
                ("author", models.JSONField(default=dict, verbose_name="原用户")),
                ("taglist", models.JSONField(default=list, verbose_name="标签表")),
                (
                    "authorkey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="原用户外键",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "db_table": "article",
            },
        ),
    ]
