# Generated by Django 4.2.8 on 2023-12-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_favorite_articlesinfo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite_articlesinfo",
            name="slug",
            field=models.CharField(max_length=256, verbose_name="标称"),
        ),
    ]
